---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create a Bastion host

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Information"
        Parameters:
          - VPCStackName
      - Label:
          default: "Bastion Configuration"
        Parameters:
          - KeyPairName
      - Label:
          default: "DNS Topic ARN"
        Parameters:
          - AddRecordSetTopicARN
      - Label:
          default: "Hosted Zone Domainname"
        Parameters:
          - HostedZone
      - Label:
          default: "Hostname"
        Parameters:
          - HostName

    ParameterLabels:
      VPCStackName:
        default: "Name of stack used to create the VPC"
      KeyPairName:
        default: "Name of key required to access the Bastion instance"
      AddRecordSetTopicARN:
        default: "Topic ARN for RecordSet creation"
      HostedZone:
        default: "Domainname to add RecodSet in"
      HostNane:
        default: "Hostname to add RecodSet in"

Parameters:
  VPCStackName:
    Type: String
    Description: "Name of the Stack used to create the VPC"
  KeyPairName:
    Type: String
    Description: "KeyPair Name"
    MinLength: 4
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-_][a-zA-Z0-9-_]*"
    ConstraintDescription: must only contain letters, numbers and dash or underscore.
  AddRecordSetTopicARN:
    Type: String
    Description: |
      The ARN of the topic used to trigger the Lambda function that in turn adds
      the recordset to the associated hosted zone
  HostedZone:
    Type: String
    Description: |
      Name of the hosted zone to add the DNS entry to (domainname)
  HostName:
    Type: String
    Description: |
      Name of host to use for the bastion

Conditions:
  AddRecordSet: !Not [!Equals [!Ref AddRecordSetTopicARN, ""]]

Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: false
      ImageId: ami-29ae2546 # Amazon Linux 2 ami for eu-central-1
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              !Sub "${VPCStackName}-SubnetPublic"
          GroupSet:
            - Fn::ImportValue:
                  !Sub "${VPCStackName}-SGDMZ"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y tcpdump mariadb telnet python-pip
          yum update -y
      Tags:
        - Key: "Name"
          Value: "Bastion host"
        - Key: "Application"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Application"
        - Key: "Environment"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Environment"
  RecordSetForBastionHost:
    Type: Custom::IPv4
    Properties:
      ServiceToken: !Ref AddRecordSetTopicARN
      Source: !Sub "${HostName}.${HostedZone}"
      Target: !GetAtt BastionHost.PublicIp
      RecordType: A

Outputs:
  Application:
    Value: !Ref BastionHost
    Description: The Bastion Host
    Export:
      Name: !Sub "${AWS::StackName}-BastionHost"

