---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Create a RDS instance.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Information"
        Parameters:
          - VPCStackName
      - Label:
          default: "RDS Configuration"
        Parameters:
          - DBEngine
          - DBInstanceClass
          - DBInstanceID
          - DBUser
          - DBPassword
          - AllocatedStorage
      - Label:
          default: "Availability"
        Parameters:
          - MultiAZ
          - BackupRetentionPeriod

    ParameterLabels:
      VPCStackName:
        default: "Name of stack used to create the VPC"
      DBEngine:
        default: "DB Engine"
      DBInstanceClass:
        default: "DB Instance Class"
      DBUser:
        default: "DB User"
      DBPassword:
        default: "DB Password"
      AllocatedStorage:
        default: "Storage size t0 provision (def 100GB)"
      MultiAZ:
        default: "MultiAZ Deployment"
      BackupRetentionPeriod:
        default: "Backup retention period"

Parameters:
  VPCStackName:
    Type: String
    Description: "Name of the stack used to create and configure the VPC"
  DBEngine:
    Type: String
    Description: "Database Engine"
    AllowedValues: [ "mariadb", "mysql", "postgres" ]
    Default: "postgres"
  DBInstanceClass:
    Type: String
    Description: "DB Instance Class"
    AllowedValues: [ "db.t2.micro", "db.t2.small", "db.t2.medium", "db.t2.large", "db.t2.xlarge" ]
    Default: "db.t2.micro"
  DBInstanceID:
    Type: String
    Description: "Database Name"
    MinLength: 6
    MaxLength: 63
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters and be between 6 and 63 characters long.
  DBUser:
    Type: String
    Description: "Database User"
    MinLength: 4
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters and be between 6 and 16 characters long.
  DBPassword:
    Type: String
    Description: "Database Password"
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{10,40}$'
    ConstraintDescription: must contain a number, lowercase, uppercase, special character (but no /, @ or double quote), no whitespace and be between 10 and 40 characters long.
    NoEcho: true
  AllocatedStorage:
    Type: Number
    Default: 100
    Description: "Volume size (GB) t0 provision (default 100)"
  BackupRetentionPeriod:
    Type: String
    Default: 5
    AllowedValues: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35 ]
    Description: "Number of days before snapshots are being removed"
  MultiAZ:
    Type: String
    AllowedValues: [ true, false ]
    Default: false
    Description: "Setup the RDS instance in MultiAZ"

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-RDSSubnetAZ1"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-RDSSubnetAZ2"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-RDSSubnetAZ3"
      Tags:
        - Key: "Application"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Application"
        - Key: "Environment"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Environment"
  RDS:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceIdentifier: !Ref DBInstanceID
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: !Ref DBEngine
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !Ref MultiAZ
      StorageType: gp2
      PreferredBackupWindow: "01:00-03:00"
      PreferredMaintenanceWindow: "01:00-03:00"
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-SGRDS"
      Tags:
        - Key: "Name"
          Value: !Ref DBInstanceID
        - Key: "Application"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Application"
        - Key: "Environment"
          Value:
            Fn::ImportValue:
              !Sub "${VPCStackName}-Environment"

Outputs:
  RDS:
    Value: !Ref RDS
    Description: "RDS DBInstance"
    Export:
      Name: !Sub "${AWS::StackName}-RDS"
